### ISSUE TITLE
"Cannot be supported in 1.0"

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-nv-use-cases#11]
In section 3, the introductory sentence is a little confusing to me. I assume

> Several new uses cases relate to scenarios that cannot be supported in [WEBRTC10].

means

> [...] cannot be supported with the 1.0 API as it is now without factoring in potentially upcoming extensions.

For example, N11 can be supported in 1.0. Just not with the API as we have it now.

**Comment by aboba** [comment]
@lgrahl Yes, I think that is what the document is trying to say.

**Comment by aboba** [comment]
Fixed in the latest editor's draft.
