### ISSUE TITLE
N14: Already supported by 1.0?

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-nv-use-cases#12]
I don't understand N14 as it's supported by 1.0. What use case does this refer to?

**Comment by aboba** [comment]
@lgtahl It *might* refer to the abilty to transfer files without requiring the server to have an `RTCIceTransport`.  As an example, RFC 8441 defines websockets over HTTP/2, which permits multiple "streams" over a single TCP connection, and something similar could be permitted with HTTP/3.  Yet there do not yet exist APIs to support this.

On the other hand, client/server transport is outside the scope of the WEBRTC WG.

**Comment by aboba** [comment]
@lgrahl I suspect we can remove requirement N14.
