### ISSUE TITLE
N42 and N47 partly overlapping

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-nv-use-cases#127]
N42: The WebRTC connection can generate signals indicating the desired bandwidth and any demands for keyframes, and surface those to the application.

N47: The WebRTC connection can generate signals indicating demands for keyframes, and surface those to the application.

Perhaps the "and any demands for keyframes" part of N42 should be scrapped?

**Comment by alvestrand** [comment]
Keeping them orthogonal seems good to me.

BTW, N47 is probably satisfied by https://github.com/w3c/webrtc-encoded-transform/pull/215

**Comment by stefhak** [comment]
OK, perhaps we should have a table or something recording what requirements are (becoming) satisfied, and how. There is also the comment "This requirement is addressed by jitterBufferTarget, defined in [WebRTC-Extensions] Section 6." for N38.
