### ISSUE TITLE
N23: Why share media between worker and main thread?

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-nv-use-cases#13]
I'm not sure why it is required to share media between worker and main thread. Can someone elaborate which one of the mentioned use cases requires this and why?

Note that data exchange is already handled by N15, so I assume this is purely about audio/video.

**Comment by aboba** [comment]
@lgrahl Presumably this is to allow CPU-intensive processing (e.g. machine learning algorithms) without disrupting the main thread.

**Comment by aboba** [comment]
@lgrahl This is already supported for audio (via Audio Worklets) so the requirement is about efficient processing of raw video data.  Can you prepare a PR?

**Comment by lgrahl** [comment]
Unless you want me to literally copy paste that text, someone else who has more experience with "funny hats" use cases is probably better suited to tackle that topic. :slightly_smiling_face:
