### ISSUE TITLE
N20 Raw media should support various pixel formats

### ISSUE THREAD

**Issue by astojilj** [w3c/webrtc-nv-use-cases#16]
This is inferred by "raw media" in requirement N20: "The application must be able to obtain raw mediafrom the capture device.", but let's specify it in requirement that raw data needs to support various pixel formats.
ArrayBuffer, used in [ImageCapture takePhoto](https://w3c.github.io/mediacapture-image/#dom-imagecapture-takephoto) via [readAsArrayBuffer(Blob)](https://w3c.github.io/FileAPI/#readAsArrayBufferSyncSection), could be the way to implement it.

**Comment by aboba** [comment]
One might also add "audio formats" for the audio case.

**Comment by aboba** [comment]
@astojilj  Can you prepare a PR for discussion at the June Virtual Interim?

**Comment by aboba** [comment]
@astojilj Can you review the proposed changes to see if they are to your liking?

**Comment by aboba** [comment]
Merged PR; if this is not adequate, please reopen.
