### ISSUE TITLE
Allocate RAW data capture buffer as shared GPU memory buffer

### ISSUE THREAD

**Issue by astojilj** [w3c/webrtc-nv-use-cases#17]
Let's consider current data flow in processing video stream on GPU:
getUserMedia() => WebGLRenderingContext.texImage2D(HTMLVideoElement)  => processing in WebGL shaders.

An example for this is in [TensorFlow.js](https://github.com/tensorflow/tfjs-core) - after video frame is [uploaded to texture](https://github.com/tensorflow/tfjs-core/blob/27766458746bbc5da44cffcee92ef605fdc1ec5c/src/kernels/webgl/gpgpu_util.ts#L234), processing is done on GPU under fenceSync - once the sync is [signaled as ready](https://github.com/tensorflow/tfjs-core/blob/0afc3ef4ac665e344fd50744cb2ae32227e195a2/src/kernels/backend_webgl.ts#L311), data can be [read back to CPU](https://github.com/tensorflow/tfjs-core/blob/27766458746bbc5da44cffcee92ef605fdc1ec5c/src/kernels/webgl/gpgpu_util.ts#L333) without blocking.

While there is a security concern related to mapping buffers that GPU writes to, we can save a copy in WebGLRenderingContext.texImage2D(HTMLVideoElement) - if raw data buffer is [shared GPU memory buffer](https://cs.chromium.org/chromium/src/ui/gfx/gpu_memory_buffer.h).

I don't think that the engine should do this by default - it could be implemented by hinting to capture pipeline that the raw data will be used on GPU.

**Comment by aboba** [comment]
@astojilj Ability to use raw media for machine learning in an efficient manner seems important.  Can we add something general to that effect as a requirement, or do we need to be specific?

**Comment by aboba** [comment]
@astojilj  Can you prepare a PR for discussion at the June Virtual Interim?

**Comment by aboba** [comment]
@astojilj Can you review the changes to see if they are to your liking?

**Comment by aboba** [comment]
PR merged; if inadequate, please reopen.
