### ISSUE TITLE
The term "parallel forking" is overloaded and should not be used

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-nv-use-cases#3]
Requirement N02 is formulated as:

The user agent must be able to support parallel forking, including reuse of local ICE candidates and local certificates with multiple Answerers.

The justification for this is given above as:

"Also, “parallel forking” minimizes conference establishment time by allowing a participant to broadcast an Offer to a “room” abstraction (maintained on a server), with other room participants responding back directly to the Offerer, avoiding a separate discovery step."

The term "parallel forking" has proved ill-defined in the past, and has led to much lack of clarity. It should therefore be avoided.

Suggested reformulation:

In scenario description:

"Also, allowing a participant to broadcast.... ..... avoiding a separate discovery step, minimizes conference establishment time."

In requirement:

N02: The user agent must be capable of establishing multiple connections to peers without generating a separate configuration ("offer") for each connection prior to establishing the connection.

This avoids the "forking" term, without restricting the possible implementations further.

**Comment by aboba** [comment]
Suggested alternate wording seems to better get at the intended meaning.
