### ISSUE TITLE
N04: The term "early media" MUST NOT be used on its own, and MAY be removed.

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-nv-use-cases#4]
Requirement N04: "Early media must be supported".

The WG has struggled with early media for a long time, because there are multiple incompatible definitions of what it means.

In this case, the basis is "It is desirable to allow media to be received from responders before the initiator receives an answer."

We are not letting go of security here. So in order to achieve DTLS-level security, the implication is that the responder we MUST be able to encrypt the media before having a two-way handshake with the initiator, and the initiator MUST be able to decrypt the media before it "receives an answer", whatever that means.

Proposal 1: Delete the requirement as infeasible.

Proposal 2: Restate the requirement as "the initiator must be able to process media from the responder based only on the packets sent in the media stream, without requiring the responder to have access to any packet sent by the initiator subsequent to the initial announcement from the initiator".

I don't know if crypto protocols that allow us to do the reformulated version exist.

**Comment by alvestrand** [comment]
Note: TLS 1.3 "0-RTT" setup may do the trick, but I think this requires that you're resuming a previous security association.

**Comment by aboba** [comment]
Agree that "early media" is too vague.  Reality is that an initiator cannot reply to ICE connectivity checks prior to receiving the responder's ICE parameters. So the initiator needs to receive some kind of "answer" first, even if DTLS 1.3 "0-RTT" can be used.
