### ISSUE TITLE
N03: "Bandwidth limit across mesh endpoints" needs clarification or modification

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-nv-use-cases#5]
I think the intent is to impose a global limit across all media connections managed by the game, in order to avoid this single game overloading a bottleneck link. However, normal congestion control with coupled congestion controllers (automatic detection of a common bottleneck) may be a more constructive way forward.

I think it's unrealistic to ask to impose a global limit on everything running in the LAN, or even a global limit on everything running on the same machine.

**Comment by aboba** [comment]
I think that your suggested intent is what was actually meant.
