### ISSUE TITLE
Broadcasting of 1:Many

### ISSUE THREAD

**Issue by Sean-Der** [w3c/webrtc-nv-use-cases#50]
Developers are trying broadcast at a large scale. These are the issues they have brought up to me.

* Time spent encrypting/decrypting. The inability to choose CipherSuites means people are using non-HW accelerated (AES-CCM-SHA1 vs AES-GCM) the later they can use things like AES-NI.
* ICE over TCP not being ubiquitous. The ops burden of running TURN servers in high.
* Lack of DRM. They want to broadcast video that must be protected, preventing them from switching certain things over.

**Comment by aboba** [comment]
@Sean-der Low latency broadcast video with DRM (MSE) can be implemented today by streaming VP9/SVC over HTTP/gQUIC, without WebRTC or ICE.  WebTransport (and possibly WebCodecs) might offer improvements, but that kind of usage wouldn't involve peer-to-peer so it can't be considered a WebRTC-NV use case.

**Comment by aboba** [comment]
At the July 8 meeting of the WebRTC WG, there was consensus that this use case should be moved to the WebTransport use case repo once it is established.

**Comment by aboba** [comment]
We now have a new use case: [Low Latency Broadcast with Fanout](https://w3c.github.io/webrtc-nv-use-cases/#auction). 

This use case includes requirements for support of DRM support, P2P relays and transport parameters.

**Comment by jimmywarting** [comment]
hate DRM... i know why it exist but it only draws more power resources and drains my battery faster 👎
