### ISSUE TITLE
N11: "as a single message" is implementation, not requirement

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-nv-use-cases#7]
The term "It must be possible for the user agent to transfer large files as a single message" doesn't define "message", and is in direct conflict with many backpressure models.

If the requirement is restated as "It must be possible for the user agent to initiate transfer of a large file with a single API operation", it appears reasonable.

**Comment by lgrahl** [comment]
Agree. (And that single API operation should take care of handling the flow control.)
