### ISSUE TITLE
Expose SCTP sequence number through Data Channel Message object

### ISSUE THREAD

**Issue by epes** [w3c/webrtc-nv-use-cases#72]
> SCTP assigns a Stream Sequence Number to each message
https://datatracker.ietf.org/doc/html/rfc4960#section-1.5.2

It would be great if this sequence number was exposed through the Data Channel Message object to detect duplicates or message loss at the application layer without appending a sequence number to the message itself.

**Comment by jesup** [comment]
Obviously for ordered channels (without setting MaxTransmits) this is irrelevant.  

The Web API doesn't actually reference SCTP I believe and in theory could operate over different underlying protocols, but we could (if we want) define an equivalent message sequence number that could be exposed.   However I think this would need to be related to the calls to Send(), which may be different than the underlying datagram sequence numbers that SCTP would use, so we'd have to put it in the data itself.  If we have to do that, it's cleaner to let the application decide if that's needed and handle it.

If there is a 1:1 correspondence between Send() calls (and messages received) and SCTP sequence numbers, we could in theory expose it.  It does mean that any non-SCTP underlying protocol might end up having the wrap a send-sequence-number on top of their protocol (unless they have the same sort of sequence number equivalency).   I'm still not convinced it's worthwhile to do this to avoid application logic and bandwidth to add sequence numbers at the application level.

**Comment by lgrahl** [comment]
Just a note since I don't have a strong opinion on either way: The data channel API spec was abstract at first but is now very much tied to SCTP, so this should not be an issue.

**Comment by epes** [comment]
I agree that if the underlying protocol would be something other than SCTP then the effort might outweigh the benefit. I'm not familiar with how prescriptive the spec is of SCTP but if it's true that they're tied together, it doesn't seem as much effort to expose something that's already parsed and available.

**Comment by zhuker** [comment]
+1

**Comment by boivie** [comment]
SSNs may only be assigned to ordered messages, and in the sent DATA chunks, the SSN may not be set for unordered messages; https://datatracker.ietf.org/doc/html/rfc4960#section-6.6

Also, with support for interleaved messages (RFC8260), the MID replaces the SSN (and is also provided for unordered messages).

I would recommend not exposing any SCTP variables like this, but instead having the client be able to provide a "userdata" of sorts when sending a message, which would then be provided in any callbacks where a message needs to be identified. What the userdata is (object, number, ...) can be discussed separately. 

That requires native SCTP library support or could possibly be emulated in the transport interfacing the SCTP library.

**Comment by lgrahl** [comment]
Thanks for that input. Since the SSN cannot be used, the TSN makes no sense in that context, we cannot rely on ndata/RFC8260 being present all the time and transmitting a sequence number in userspace is trivial, I'd prefer to keep the web API and the underlying data channel protocol as simple as possible and make no modifications in that regard.

**Comment by epes** [comment]
Makes sense, I was not aware that the SSN was optional for unordered messages.
