### ISSUE TITLE
Support for End to End Encryption (E2EE) 

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-nv-use-cases#76]
Ability to provide end to end encryption for audio and video media. The goal is to make sure that a compromise in the cloud, including wherever the JS came from, does not result in in a loss of the private data.

**Comment by aboba** [comment]
Currently we only have a use case for ["Untrusted JS Cloud Conferencing"](https://www.w3.org/TR/webrtc-nv-use-cases/#untrusted*).  This sounds like a "Trusted JS Cloud Conferencing" use case.

**Comment by jan-ivar** [comment]
> ...including wherever the JS came from

This sounds like the existing ["Untrusted JS Cloud Conferencing"](https://www.w3.org/TR/webrtc-nv-use-cases/#untrusted*) to me. Am I wrong?

It's a bit odd it has no mention of E2EE perhaps, but I suppose it's a means to an end here? E.g. I see no other way to satisfy N28.

Can we close this?

**Comment by fluffy** [comment]
Yep, I agree, it is all getting at the same stuff and we can close this.
