### ISSUE TITLE
What is a "node" in the Low latency Broadcast with Fanout use case?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-nv-use-cases#85]
The N39 requirement in the [§ 3.2.2 Low latency Broadcast with Fanout](https://w3c.github.io/webrtc-nv-use-cases/#auction) use case reads:
- _"A node must be able to forward media received from another node to a third node. Applications require access to encoded chunk metadata as well as information from the RTP header to provide for timing, media configuration and congestion control. This includes a mechanism for a relaying peer to obtain a bandwidth estimate."_

I've received a question I couldn't answer about what a "node" is in this case, so this may require clarification.
1. If "node" is a user agent already in a position to perform playback ("relaying peer"), then this is not a new requirement
2. If "node" includes some sort of in-network intermediary, and the goal is to ensure forwarding by entities other than those involved in the session, we're potentially into sframe territory and that hasn't worked out well thus far. This also sounds more IETF than W3C.

More clarity seems needed.

I'd also like to understand whether optimizing [existing relay functionality](https://webrtc.github.io/samples/src/content/peerconnection/multiple-relay/) to skip unnecessary decode and re-encode would satisfy this requirement, challenging whether exposing more surface to "Applications" is a necessary requirement.

**Comment by aboba** [comment]
Good question. My assumption was that "node" was equivalent to "user agent" because N39 mentions "Applications" which I assumed meant JS applications running in the browser.  With respect to whether the requirements are new, N35 talks about the ability to resend encoded media to multiple parties, but doesn't talk about metadata or bandwidth estimates. So it does seem like requirements N39 and N41 include unique aspects.

**Comment by alvestrand** [comment]
If the node is not an user agent (browser), it's not a matter for the WEBRTC WG, so let's assume it's an user agent.
The part of the requirement that is not covered by anything we've currently done (AFAIK) is the 2nd and 3rd sentence.
If we have other requirements in webrtc-nv-use-cases that cover the 2nd and 3rd sentence, please enumerate.
